name:                Lambda
version:             0.0.0.0
github:              "andrewerf/Lambda"
license:             BSD-3-Clause
author:              "Andrey Aralov"
maintainer:          "andrew-aralov@yandex.ru"
copyright:           "2024 Andrey Aralov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Lambda#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=incomplete-patterns

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  dependencies:
    - array
    - megaparsec
    - raw-strings-qq

executables:
  LambdaRepl:
    main: Main.hs
    source-dirs: app/LambdaRepl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lambda
  LambdaReplWeb:
    main: Main.hs
    source-dirs: app/LambdaReplWeb
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Lambda
      - text
      - websockets
      - snap-core
      - snap-server
      - websockets-snap
      - optparse-applicative

tests:
  Lambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lambda
    - HUnit
    - hspec
    - hspec-contrib
