version: "3.0"
services:
  backend:
    build:
      dockerfile: Dockerfile-backend
    command:
      - "--"
      - "-h"
      - "0.0.0.0"
      - "-p"
      - "8080"
      - "--ssl-port"
      - "4430"
      - "--cert"
      - "/etc/letsencrypt/live/whateveritis.strangled.net/fullchain.pem"
      - "--key"
      - "/etc/letsencrypt/live/whateveritis.strangled.net/privkey.pem"
    ports:
      - "8080:8080"
      - "4430:4430"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
  frontend:
    image: docker.io/httpd:2.4
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "8800:80"
    restart: always
